<!DOCTYPE html>
<html>
<head>
    <title>La Casa de IQ - Gerenciador de Sala VIP</title>
</head>
<body>
    <h1>La Casa de IQ - Gerenciador de Sala VIP</h1>
    <form id="gerenciadorForm">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome"><br><br>

        <label for="dataEntrada">Data de Entrada:</label>
        <input type="date" id="dataEntrada" name="dataEntrada"><br><br>

        <label for="dataTermino">Data de Término (30 dias a partir da entrada):</label>
        <input type="text" id="dataTermino" name="dataTermino" readonly><br><br>

        <input type="button" value="Adicionar Pessoa" onclick="adicionarPessoa()">
    </form>

    <h2>Pessoas na Sala VIP:</h2>
    <ul id="listaPessoas"></ul>

    <script>
        function calcularDataTermino(dataEntrada) {
            var dataTermino = new Date(dataEntrada);
            dataTermino.setDate(dataEntrada.getDate() + 30);
            var dd = String(dataTermino.getDate()).padStart(2, '0');
            var mm = String(dataTermino.getMonth() + 1).padStart(2, '0'); // Janeiro é 0!
            var yyyy = dataTermino.getFullYear();
            return yyyy + '-' + mm + '-' + dd;
        }

        function adicionarPessoa() {
            var nome = document.getElementById("nome").value;
            var dataEntrada = document.getElementById("dataEntrada").value;

            if (nome.trim() === "" || dataEntrada === "") {
                alert("Por favor, preencha o nome e a data de entrada.");
                return;
            }

            var dataTermino = calcularDataTermino(new Date(dataEntrada));

            var listaPessoas = document.getElementById("listaPessoas");
            var novaPessoa = document.createElement("li");
            novaPessoa.innerHTML = nome + " - Data de Término: " + dataTermino;
            listaPessoas.appendChild(novaPessoa);

            document.getElementById("gerenciadorForm").reset(); // Limpa o formulário
        }
    </script>
</body>
</html>
